on: [push]

name: Stereo Vision Push

jobs:
  publish-code:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors' 
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Restart service
      run: sudo systemctl status utility-telegram-bot.service
