name: Sync and Build
on:
  push:
    branches:
      - new_main
  workflow_dispatch:
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
  build:
    runs-on: self-hosted
    steps:
    - name: Build C File
      run: gcc -fPIC -shared -o disparity_calc.so disparity_calc.c
