name: Sync and Build
on:
  push:
    branches:
      - new_main
  workflow_dispatch:
jobs:
  sync_build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Build C File
        run: gcc -fPIC -shared -o disparity_calc.so disparity_calc.c
