name: Sync Files
on:
  push:
    branches:
      - new_main
  workflow_dispatch:
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
